### PR TITLE
Add Bloodhound to list of implementations.

### PR DESCRIPTION
**Pull request by daninnewyork**
To install and verify:

`npm i bloodhound-promises`
`npm run-script verify`

### CODE REVIEW

**Comment by briancavalier** [comment]
Hey @daninnewyork. Unfortunately, this PR seems to contain a merge commit.  Could you please rebase/cleanup so that it only contains a single commit that updates implementations.md?  Thanks!

**Comment by briancavalier** [comment]
Just ran the unit tests, and they all pass.  Looking good!  If you can fix up the commits (see prev comment), I'll be happy to merge.

**Comment by daninnewyork** [comment]
Sorry about that! I'm still new to git -- going to close this request and try again.

**Comment by briancavalier** [comment]
No worries @daninnewyork, thanks for sending a new PR.

**Pull request closed without merging**
