### PR TITLE
Add "Quick Promise" to the Conformant Implementation list.

### PR DESCRIPTION
**Pull request by benlau**

### CODE REVIEW

**Comment by bergus** [comment]
Thanks! It might be more interesting to add QML to the In Other Languages section :-)

**Comment by benlau** [comment]
oh , sorry .

Done. It is changed to Other Language section.

**Comment by domenic** [comment]
Am I reading this right that you managed to hook up the Promises/A+ tests to your implementation, despite it being written in another language? If so, very impressive!

**Comment by benlau** [comment]
thx! yes! I have run the promises-aplus-test over my implementation. 

However, it is not completely another language , since the core part of QML is also Javascript. I just did few string replace call to remove QML specific syntax then pass it to promises-aplus-test .

**Comment by domenic** [comment]
Ah I see, very cool! Do all the tests pass? I notice you had a "TODO: implement 2.3.3," which did not seem promising.

**Comment by benlau** [comment]
oh... I have forgotten to remove the comment. In fact , all the test cases are already passed. 

The result:
https://travis-ci.org/benlau/quickpromise/builds/62967035

**Comment by briancavalier** [comment]
@benlau I just ran the tests on a local clone.  All passed.  Nice work.

I did notice that in the current master branch, there is still quite a lot of debug output being logged when the promises-aplus tests run.  No big deal, just wanted to point it out.

@domenic Any further concerns?

**Comment by domenic** [comment]
LGTM!

**Comment by benlau** [comment]
Thank you!

**Pull request merged**
