### PR TITLE
Add Hprose to the implementations list.

### PR DESCRIPTION
**Pull request by andot**
```javascript
var hprose = require("hprose");
var promisesAplusTests = require("promises-aplus-tests");

promisesAplusTests(hprose, function (err) {
    // All done; output is in the console. Or check `err` for number of failures.
});
```

It can pass all tests.

### CODE REVIEW

**Comment by bergus** [comment]
Hi, could you please squash these commits into a single one?
Also I'm not sure wether this lib needs two entries in the frameworks table; the promise implementation does not seem to differ between them except for the used module definition pattern.

**Comment by andot** [comment]
OK, I removed the hprose for html5, only left hprose for node.js.

**Comment by briancavalier** [comment]
@andot Good job, tests pass.  One suggestion: I think it would be helpful if you would list `promises-plus-tests` as a `devDependency` in package.json, and also provide a convenient way to run them, such as adding an npm script, like `npm run aplus-tests`.

Also, as @bergus asked, please squash to a single commit.

**Comment by andot** [comment]
OK, I squash to a single commit, now.

**Comment by domenic** [comment]
Hmm, trying to do `npm install` after cloning https://github.com/hprose/hprose-nodejs gives the following error:

```
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/promises-plus-tests
```

Looks like a typo in the package.json?

**Comment by andot** [comment]
Fixed this bug.

**Comment by domenic** [comment]
Merged as 3c76b7fed3a1c451d47f2f8eef8d58aa385e678d; thank you!

**Pull request closed without merging**
