### PR TITLE
adding welsh

### PR DESCRIPTION
**Pull request by kode4food**

### CODE REVIEW

**Comment by bergus** [comment]
What exactly does "*but not really*" refer to?

**Comment by kode4food** [comment]
It refers to the Deferreds impl that is bundled along with the A+ Promises -- they were originally the only thing I included when I started the project a few days ago.

But does it matter?  The promises impl passes the suite, which is the only qualification as far as the list and logo are concerned

**Comment by briancavalier** [comment]
Thanks @kode4food.

> But does it matter?

I think @bergus was honestly just curious--the phrase caught my attention, too, to be honest.  Yes, you're right, as long as it passes the tests, you're good.  I'll give it a go later tonight.

**Comment by kode4food** [comment]
Fair enough.  The ultimate goal of the library is to create semi-interchangeable Twisted-like Deferreds and Promises, so I didn't want to push the idea that this was only a A+ Promises impl.

**Comment by kode4food** [comment]
to test, you can either do `npm run-script compliance` or just run the `gulp` build script since I'm sucking the mocha tests into my own

**Comment by briancavalier** [comment]
Got it, thanks.  And thanks for the instructions on running the tests.

**Comment by briancavalier** [comment]
Yep, all tests pass.  Good job, @kode4food.

**Comment by kode4food** [comment]
fantastic, thanks!

**Pull request merged**
