### PR TITLE
Add creed

### PR DESCRIPTION
**Pull request by briancavalier**
Experimenting with a [new impl](https://github.com/briancavalier/creed), so figured I'd add it.  To run the tests: clone, `npm install && npm test`.

### CODE REVIEW

**Comment by bergus** [comment]
Nice! I think I need to pilfer those tests and perf benchmarks, as I'm pretty much programming against the same API [\[1\]](https://github.com/bergus/F-Promise) (but haven't finished yet, though I'm constantly passing A+ since long) :-)

So are you supporting parametric types, i.e. promises for promises, with `Promise.fulfill`? Btw, I'm missing `Promise.of`, to complete the fantasy-land monad?

**Comment by briancavalier** [comment]
Hey, thanks @bergus.  Sure, feel free to pilfer :)

Yeah, it supports parametricity via `fulfill`.  `of` is actually there ... try `console.log(fulfill().constructor.of);` (similarly `fulfill().constructor.empty` for the monoid instance).  I decided not to directly expose *any* constructors (except the ES2015 polyfill, which shouldn't have `of` anyway), only pseudo ctors like `runPromise`, `runNode`, `resolve`, etc.  So you can't get at `of` easily right now, and I'm still deciding exactly how to handle that.

I see that you [exported `from`](https://github.com/bergus/F-Promise/blob/master/src/aplus.js#L25) as an alias for `resolve`, which I like a lot.   I've been thinking of doing that also, and then exporting `of` as an alias for `fulfill`.  The problem there is that `of` isn't friendly for ES2015 imports (`import { of } from 'blah';` is a syntax error :( ).  So, I've been thinking of naming it `just` instead, like [over in most.js](https://github.com/cujojs/most/blob/master/most.js#L19).

**Comment by briancavalier** [comment]
@bergus I'll probably pilfer the name `promise.fork`.  Creed has an internal method that is *very* similar, and you found a good name for it :D

**Comment by bergus** [comment]
I didn't have time yet to explore your implementation, but I'll surely have a look :-)
Notice that `Promise.from` is not exactly an alias to `resolve`, as it doesn't create a new instance if you pass in a promise. It's more like the `Promise.cast` that [did not make it into ES6](https://esdiscuss.org/topic/promise-cast-and-promise-resolve), probably for good reasons.
Also, `.fork` might collide with the [`Task` cancellation draft from GTOR](https://github.com/kriskowal/gtor/blob/master/cancelation.md), which I didn't care about as my promise (callback)s are implicitly cancellable, but YMMV.

**Comment by briancavalier** [comment]
I believe `Promise.resolve` is [allowed to return its argument](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-promise.resolve), as well, so `resolve` and `from` can be aliases.  FWIW, creed implements `resolve` in a similar way: it will return its argument or a promise nearer to the ultimate value.

Thanks for the reminder about gtor.  I forgot about that ...

**Comment by domenic** [comment]
LGTM!

**Comment by briancavalier** [comment]
Thanks for the review, @domenic!

**Pull request merged**
