### PR TITLE
added Lifelong.Promise for Typescript

### PR DESCRIPTION
**Pull request by RonNewcomb**
added Lifelong.Promise for Typescript 2.0+

### CODE REVIEW

**Comment by briancavalier** [comment]
Hi @RonNewcomb.  We need to be able to verify that your implementation passes the test suite.

It's typical for implementations to provide a package.json that allows running the Promises/A+ test suite via `npm test`, or a Makefile, etc.  Could you please set that up in your repo, and/or add a section to Lifelong.Promise's README that shows how to run the promises-aplus tests against your implementation, so that we can verify?  Thanks!

**Comment by RonNewcomb** [comment]
Added the test suite to my repo; use `npm test`

**Comment by briancavalier** [comment]
Thanks @RonNewcomb.  Nice work.  Lifelong passes the tests, so I'm good with merging this.

A tip though.  Rather than copying the source code the promises-aplus-tests into your repo, it would be more typical to include a package.json file at the top level of the repo that lists `promises-aplus-tests` as a `devDependency`, and has an `npm test` script that runs them.  Check out how other implementation have done it in their root level package.json.

**Comment by RonNewcomb** [comment]
Will do.  Thanks for the tip.

**Pull request merged**
